SitefinityCalendar/SitefinityCalendar/Mvc/Models/EventsWidgetModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using Telerik.Sitefinity.Events.Model;

namespace SitefinityCalendar.Mvc.Models
{
	public class EventsWidgetModel
	{
		public IQueryable<Calendar> Calendars { get; set; }
		public IQueryable<Event> Events { get; set; }
	}
}

SitefinityCalendar/SitefinityCalendar/Mvc/Controllers/EventsController.cs
using SitefinityCalendar.Mvc.Models;
using SitefinityCalendar.Services.Contracts;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Telerik.Sitefinity.Modules.Events;
using Telerik.Sitefinity.Mvc;

namespace SitefinityCalendar.Mvc.Controllers
{
	[ControllerToolboxItem(Name = "EventsWidget", Title = "Events Widget", SectionName = "Custom Widgets")]
	public class EventsController : Controller
	{
		private readonly IEventsService _eventService;
		private readonly EventsManager _manager;

		public EventsController(IEventsService eventService, EventsManager manager)
		{
			_eventService = eventService;
			_manager = manager;
		}

		// If calendarTitle is null, retrieves all events sorted by start date.
		// If calendarTitle is not null, retrieves events filtered by calendar title and sorted by start date.
		public ActionResult Index(string calendarTitle = null)
		{
			_eventService.CreateTenEvents();

			var events = string.IsNullOrEmpty(calendarTitle)
				? _eventService.GetAllEvents()
				: _eventService.QueryEventsByCalendar(calendarTitle);

			var calendars = _manager.GetCalendars();

			var result = new EventsWidgetModel()
			{
				Calendars = calendars,
				Events = events,
			};

			return View(result);
		}

		// Retrieves all events sorted by the value of sortBy parameter.
		public ActionResult Order(string sortBy)
		{
			var events = _eventService.QueryEvents(sortBy);

			var calendars = _manager.GetCalendars();

			var result = new EventsWidgetModel()
			{
				Calendars = calendars,
				Events = events,
			};

			return View("Index", result);
		}
	}
}

SitefinityCalendar/SitefinityCalendar/Mvc/Views/Events/Index.cshtml
@using Telerik.Sitefinity.Web;
@using SitefinityCalendar.Mvc.Models
@model EventsWidgetModel

<link href="@Url.Content("~/ResourcePackages/EventsWidget/css/main.css")" rel="stylesheet" type="text/css" />

@{
	string currentPageUrl = SiteMapBase.GetActualCurrentNode().UrlName.ToString();
}


<div class="events-panel">
	<div class="calendar-buttons">
		<div class="sort-buttons btn-group" role="group">
			<a href="@Url.Action("Index", "Events")" class="btn btn-primary">All Events</a>
			@foreach (var ca in Model.Calendars)
			{
				<a href="@Url.Action("Index", "Events", new { calendarTitle = ca.Title })" class="btn btn-primary">@ca.Title</a>
			}
			<a href="@Url.Action("Order", "Events", new { sortBy = "start" })" class="btn btn-primary">Sort by Start Date</a>
			<a href="@Url.Action("Order", "Events", new { sortBy = "end" })" class="btn btn-primary">Sort by End Date</a>
		</div>
	</div>
	<div class="events">
		@foreach (var ev in Model.Events)
		{
			<div class="event">
				<div class="event-content">
					<h3><a href="@Url.Content("~/" + currentPageUrl + ev.ItemDefaultUrl)">@ev.Title</a></h3>
					<p>Start: @ev.EventStart.ToString("MMMM d, h:mm tt")</p>
					<p>End: @string.Format("{0:MMMM d, h:mm tt}", ev.EventEnd)</p>
				</div>
			</div>
		}
	</div>
</div>